
###

### Awards and Honors
2017	    Registration and Travel Scholarship, Summer Institute in Statistics for Big Data, training in reproducible research in biomedical big data, supervised methods for                 statistical machine learning, and unsupervised methods for statistical machine learning, University of Washington, Department of Biostatistics, Seattle, WA

2017	    First Place Postdoctoral Fellow Poster Award, Maryland Genetics, Epidemiology and Medicine (MD-GEM) Genetics Research Day, Johns Hopkins Bloomberg School of Public                Health,Johns Hopkins School of Medicine, and the National Human Genome Research Institute, Baltimore, MD

2015	    Third Place Poster Travel Award, International Imaging Genetics Conference (IIGC) 

2014	    First Place Poster Travel Award, International Imaging Genetics Conference (IIGC) 

2013	    Student Travel Grant Award, International Neuroinformatics Coordinating Facility (INCF) Short Course On Neuroinformatics, Neurogenomics, and Brain Disease,                        Fraueninsel, Chiemsee, Germany

2011	    Third Place Oral Presentation, Biomedical Sciences Graduate Program (BSGP) Student Research Day 

2005 – 2009	Dean’s List, University of New Mexico

2005 – 2009	Presidential Scholarship, University of New Mexico

2005 – 2009	Frank O. and Sadie M. Lane Endowed Women in Science Scholarship, University of New Mexico
