###
###
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;

## Publications {.tabset .tabset-fade}
&nbsp;

### First Author Publications
1. **Wright C.\***, Rajpurohit A.\*, Jaffe A., Burke, E., Williams, C., Collado-Torres, L., Kimos, M., Brandon N., Cross A.J., Weinberger D. R., and Shin J. H. (2019) Comprehensive assessment of multiple biases in small RNA sequencing reveals significant differences in the performance of widely used methods. BMC Genomics. 20(1):513. PMID: [1226924](https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-019-5870-3)
\* These authors contributed equally to this work.

2.	Rosenberg A. Z\*., **Wright C\***., Fox-Talbot K., Rajpurohit A., Williams C., Porter C., Foulke-Abel J, Kovbasnjuk O., McCall M. N., Shin J. H.,  Haluska, M. K. (2018) xMD-miRNA-seq to generate near in vivo miRNA expression estimates in colon epithelial cells. Scientific Reports. 8(1):9783. PMID: [29955168](https://www.ncbi.nlm.nih.gov/pubmed/29955168)
\* These authors contributed equally to this work.

3.	**Wright C.**, Ross D. A., and Weinberger D. R. (2018) Small RNAs may answer big questions in mental illness. Biological Psychiatry. 83(1):e1. PMID: [29173708](https://www.ncbi.nlm.nih.gov/pubmed/?term=29173708)

4.	**Wright C.**, Shin J. H., Jaffe A., Rajpurohit A., Brandon N., Cross A., Hyde T. M., Kleinman, J. E., and Weinberger D. R. (2017) Altered expression of histamine signaling genes in Autism Spectrum Disorder. Translational Psychiatry. 7(5):e1126. PMID: [28485729](https://www.ncbi.nlm.nih.gov/pubmed/?term=28485729)

5.	**Wright C.**, Gupta C. N., Chen J., Patel V., Calhoun V.D., Ehrlich S., Wang L., Bustillo J. R., Perrone-Bizzozero N., and Turner J. A. (2016) Polymorphisms in MIR137HG and microRNA-137 regulated genes influence gray matter structure in schizophrenia. Translational Psychiatry. 6:e724. PMID: [26836412](https://www.ncbi.nlm.nih.gov/pubmed/?term=26836412)  

6.	**Wright C.**, Calhoun V., Ehrlich S., Wang L., Turner J.A., and Perrone-Bizzozero N. (2015)
Meta gene set enrichment analyses link miR-137-regulated pathways with schizophrenia risk. Frontiers in Genetics. 6:147. PMID: [25941532](https://www.ncbi.nlm.nih.gov/pubmed/?term=25941532)

7.	**Wright C.**, Turner J.A., Calhoun V.D. and Perrone-Bizzozero N. (2013) Potential impact of miR-137 and its targets in schizophrenia. Frontiers in Genetics. 4:58. PMID: [23637704](https://www.ncbi.nlm.nih.gov/pubmed/?term=23637704) 

### Secondary Author Publications

1. Savonen, C., **Wright, C.**, Hoffman, A.M., Muschelli, J., Cox, K., Tan, F.J., and Leek, J.T., (2022). Open-source Tools for Training Resources – OTTR. I Journal of Statistics and Data Science Education, [doi: 10.1080/26939169.2022.2118646](https://doi.org/10.1080/26939169.2022.2118646)\

2. The Genomic Data Science Community Network (2022). Diversifying the genomic data science research community. Genome Res. 32, 1231–1241. PMID: [35858750](https://pubmed.ncbi.nlm.nih.gov/35858750/) 

3.	Maphis N.M., Jiang S., Binder J., **Wright C.**, Gopalan B., Lamb B.T., and Bhasker K. (2017) Whole genome expression analysis in a mouse model of tauopathy identifies MECP2 as a possible regulator of tau pathology. Frontiers in molecular neuroscience. 10:69. PMID: [28367114](https://www.ncbi.nlm.nih.gov/pubmed/?term=28367114)

4.	Patel V.S., Kelly S., **Wright C.**, Gupta C. N., Arias-Vasquez A., Perrone-Bizzozero N., Ehrlich S., Wang L., Bustillo J.R., Morris D., Corvin A., Cannon D.M., McDonald C., Donohoe G., Calhoun V.D., and Turner J.A. (2015) MIR137HG risk variant rs1625579 genotype is related to corpus callosum volume in schizophrenia, Neuroscience Letters. 602: 44. PMID: [26123324](https://www.ncbi.nlm.nih.gov/pubmed/?term=26123324)

5.	Gupta C.N., Chen J., Liu J., Damaraju E., **Wright C.**, Perrone-Bizzozero N.I., Pearlson G., Luo L., Michael A.M., Turner J.A., and Calhoun V.D. (2015) Genetic markers of white matter integrity in schizophrenia revealed by parallel ICA. Front. Hum. Neurosci. 9:100. PMID: [25784871](https://www.ncbi.nlm.nih.gov/pubmed/?term=25784871) 

6.	Hass J., Walton E., **Wright C.**, Beyer A., Scholz M., Turner J., Liu J., Smolka M.N., Roessner V., Sponheim S.R., Gollub R.L., Calhoun V.D., and Ehrlich S. (2015) Associations between DNA methylation and schizophrenia-related intermediate phenotypes - a gene set enrichment analysis. Prog Neuropsychopharmacol Biol Psychiatry. 59:31. PMID: [25598502](https://www.ncbi.nlm.nih.gov/pubmed/?term=25598502) 

7.	Savage D. D., Rosenberg M. J., Wolff C. R., Akers K. G., El-Emawy A., Staples M. C., Varaschin R. K., **Wright C.**, Seidel J. L., and Caldwell K. K. (2010). Effects of a novel cognition-enhancing agent on fetal ethanol-induced learning deficits. Alcoholism: Clinical and Experimental Research. 34: 1793. PMID: [20626729](https://www.ncbi.nlm.nih.gov/pubmed/?term=20626729) 


### Preprints
<!-- 1. Savonen, C., **Wright, C.**, Hoffman, A.M., Muschelli, J., Cox, K., Tan, F.J., and Leek, J.T., (2022). -->
<!-- Open-source Tools for Training Resources – OTTR. [arXiv:2203.07083](https://arxiv.org/abs/2203.07083). -->

1. **Wright, C.**, Meng Q., Breshock, M.R., Atta, L., Taub, M.A.,  Jager, L.R., Muschelli, J., and Hicks, S.C. Open Case Studies: Statistics and Data Science Education through Real-World Applications (2023). [arXiv.2301.05298](https://arxiv.org/abs/2301.05298)

2. Savonen, C., **Wright, C.**, Hoffman, A.M., Humphries, E.M., Cox, K.E.L., Tan, F.J., and Leek, J.T. Motivation, inclusivity, and realism should drive data science education (2023) [arXiv:2305.06213](https://arxiv.org/abs/2305.06213)


