###
###
&nbsp;


## Service
Reviewer for: Bioinformatics, Open Biology, The World Journal of Biological Psychiatry, Biological Psychiatry, JAMA Psychiatry, Cell Genomics, Journal of Statistics and Data Science Education, and Harvard Data Science Review. 


**2025** [ITCR Trainee Symposium Planning Committee Member](https://sites.google.com/view/itcrtraineesymposium/previous-years)

**2024** [ITCR Annual Meeting Planning Committee Member](https://itcr2024.org/organizing-committee)

**2024** [ITCR Trainee Symposium Planning Committee Member](https://itcrtrainee-2024.emory.edu/about/index.html)

**2023** ITCR Annual Meeting Planning Committee Member

**2022** [Baltimore Community Engagement Committee Member](https://publichealth.jhu.edu/about/key-commitments/baltimore-community-engagement)

**2022** [Project Lead for Democracy Data Science Hack-a-thon](https://100percentdemocracy.substack.com/p/a-democracy-data-science-hack-a-thon?s=w) -- [GitHub](https://github.com/carriewright11/Party_at_the_polls)

**2022**        Reviewer for [Diversity Summer Internship Program for Undergraduates (DSIP)](https://publichealth.jhu.edu/about/inclusion-diversity-anti-racism-and-equity-idare/diversity-summer-internship-program-for-undergraduates) 2022 Applicants

**2020**        [HeartSmiles](https://www.heartsmilesmd.com/) Success Session Guest Speaker. May 1st, 2020.

**2019**        Career calls with [Odyssey STEM Academy](https://odyssey.pusdschools.net/) Scholars

**2019**       Volunteer Judge for the Johns Hopkins 4th Annual Excellence in Diversity Symposium

**2019**        Volunteer for [B'more for Healthy Babies (BHB)](https://www.healthybabiesbaltimore.com/)'s 10th Annual Night at the Aquarium

**2018**		Volunteer for AAAS at the USA Science and Engineering Festival

**2013**     	Volunteer Judge for the	Central New Mexico Research Challenge 

**2013**		Health Sciences Student Council Representative Alternate, University of New Mexico

**2011**     		Social co-chair of the Biomedical Sciences Graduate Student Society, University of New 
Mexico

**2001 – 2005**	Volunteer at the Explora Science Center, Albuquerque, NM
