###
###
&nbsp;

## Teaching Experience
2019 **Course Instructor**
[Johns Hopkins Center for Talented Youth](https://cty.jhu.edu/), Baltimore, MD
“Introduction to Biomedical Sciences”
Designed and taught a course about Biomedical Sciences to high school students in Abu Dhabi and Ajman in the United Arab Emirates (approx 15 students each)

2018 **Teaching Assistant**
[Baltimore Underground Science Space](http://www.bugssonline.org/), Baltimore, MD
“R you interested in big data analysis?”
Assisted with R programming analysis one-on-one with students

2018 **Teaching Assistant**
[Baltimore Underground Science Space](http://www.bugssonline.org/), Baltimore, MD
“Go with your guts! (And the billions of bacteria in them): A personal microbiome course”
Assisted with R programming analysis one-on-one with students

2017 **Course Instructor**
[Baltimore Underground Science Space](http://www.bugssonline.org/), Baltimore, MD
“Adventures in BIG DATA Analysis"
Designed and taught a course on data analysis using R to approximately 20 students

2017 **Research Mentor**
Department of Clinical Sciences, Lieber Institute for Brain Development, Johns Hopkins School of
Medicine, Baltimore, MD
Trained and guided a Johns Hopkins undergraduate Student Researcher, Jane Brusilovsky, through a
gene expression research project

2017 **Research Mentor**
Department of Clinical Sciences, Lieber Institute for Brain Development, Johns Hopkins School of
Medicine, Baltimore, MD
Trained and guided a research associate, Nina Rajpurohit, through a gene expression research project

2013 **Teaching Assistant**
Department of Neurosciences, University of New Mexico, Albuquerque, NM
“Introduction to Neurobiology”, Biomed 509 taught by Donald Partridge, Ph.D.
Assisted with grading, class organization, and discussions

2013 **Research Mentor**
Mind Research Network, Albuquerque, NM
Trained and guided an undergraduate Student Researcher, Daniel Astorga, through an imaging genetics
research project

2007 **Student Tutor**
Department of Chemistry, University of New Mexico, Albuquerque, NM
“Organic Chemistry”, Chem 301 taught by Lisa Whalen, Ph.D.
Tutored two undergraduate students

2005 **Class Instructor**
[Explora Science Center](https://www.explora.us/), Albuquerque, NM
Taught a variety of science courses to children age 3-12


